export const NavigationRoutes = {
    onbording:'OnBording',
    home:'Home',
    history:'History',
    profile:'Profile',
    usertype:'UserType',
    chats:'Chats',
    bottom: 'BootamTabNavigation',
    signup:'SignUp',
    login:'Login',
    loginotpverification:'LoginOtpVerification',
    carmechanic:'CarMechanic',
    addaddress:'AddAddress',
    manageaddress:'ManageAddress',
    detail:'Details',
    checkout:'Checkout',
    selectdate:'SelectDate',
}