export const Strings = {
    title:"Reliable Car Repairs at Your Fingertips!",
    desc:"Find expert mechanics, book services, and get your car fixed hassle-free—anytime, anywhere!",
    usertypeText:"Select User Type",
    signupTitle:"Please Fill the Form!",
    fname:"Full Name",
    email:"Email ID",
    mobile:"Mobile Number",
    dummy:"Dummy",
    plusaddAddress:"+ Add another address",
    addAddress:"Add Address",
    searchAdd:"Search Address",
    company:"Company, Building",
    flooe:"Floor",
    tower:"Tower",
    landmark:"Landmark",
    phone:"Enter Phone Number",
    info:"fill your information below or register with your social account",
    verification:"Get verification code",
    signup:"Sign Up Now",
    newhere:"New Here?",
    verificationText:"Verification Code",
    otpsent:"OTP has been send to +1234567890",
    getotp:"Didn’t Get OTP",
    sendotp:"Send OTP (SMS)",
    addaddress:'Add Address For Batter Navigation',
    alreadyDone:'Note: Ignore If Your Have Already Done😄',
    clickHere:"Click Here To Add Address",
    location:"New Delhi,INDIA",
    recomanded:"Recommended Services",
    categori:"Categories",
    mechanic:"Car Mechanic",
    easygo:"EasyGo Electricians",
    serviceDesc:"Your trusted electricians shop for all electrical supplies, wiring, lighting, and repair services. Quality products and expert solutions for homes and businesses.",
    services:'Services',
    detail:"Details",
    checkout:"Checkout",
    addVehicleInfo:"Add Vehicle Information",
    addVehicleImg:"Upload Vehicle Image",
    uploadLicense:"Upload Driving License",
    uploadInsurance:"Upload Vehicle Insurance",
    profilename:'Alexander D’Souza',
    policy:'Cancelation Policy',
    terms:'Terms & conditions',
    lorem:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    gettouch:'Get in Touch',
    faqs:'FAQs',
    booking:'Your Service Has Been ',
    success:'Booked Successfully.',
    rate:'Select Rate',
    name:'Varshil Electrical',
    dateInfo:'Sat, Aug 12th at 3:30 PM Booking ID : 87HJBHJ87',
    amountpaid:'Amount Paid : $95',
    homeaddress:'21 Cyrenius Avenue, Plainville,ct, 6062 United States',
    time:'Sat, Aug 12th at 3:30 PM',
    
}