const Images = {
    arrowright:require('./images/arrowright.png'),
    blanckstar:require('./images/blanckstar.png'),
    camera:require('./images/camera.png'),
    carpenter:require('./images/carpenter.png'),
    cart:require('./images/cart.png'),
    carwash:require('./images/carwash.png'),
    electrician:require('./images/electrician.png'),
    electricimg:require('./images/electricimg.png'),
    filter:require('./images/filter.png'),
    headphone:require('./images/headphone.png'),
    imgfive:require('./images/imgfive.png'),
    imgfour:require('./images/imgfour.png'),
    imgone:require('./images/imgone.png'),
    imgthree:require('./images/imgthree.png'),
    imgtow:require('./images/imgtow.png'),
    loginbanner:require('./images/loginbanner.png'),
    mappoint:require('./images/mappoint.png'),
    mechanic:require('./images/mechanic.png'),
    OTP:require('./images/OTP.png'),
    pdfupload:require('./images/pdfupload.png'),
    pestcontroal:require('./images/pestcontroal.png'),
    plumber:require('./images/plumber.png'),
    Signup:require('./images/Signup.png'),
    star:require('./images/star.png'),
    successtick:require('./images/successtick.png'),
    viewcart:require('./images/viewcart.png'),
    home:require('./images/home.png'),
    chats:require('./images/chats.png'),
    history:require('./images/history.png'),
    user:require('./images/user.png'),
    backbtn:require('./images/backbtn.png'),
    homeicon:require('./images/homeicon.png'),
    businessicon:require('./images/businessicon.png'),    
    eadit:require('./images/eadits.png'),    
}

export default Images